'use strict';
const $=id=>document.getElementById(id);let history=[],baseline=[],predictions=[],testResults=[],original=true,busy=false,cancelled=false,currentSeed=null;
const seedDefault=20260928,fmt=n=>String(n).padStart(2,'0'),pause=()=>new Promise(r=>setTimeout(r,0));
function status(t){$('status').textContent=t}
function setSeed(seed){currentSeed=integer(seed,0,4294967295,'シード');$('seed').textContent=String(currentSeed)}
function initializeSeed(){const displayed=$('seed').textContent.trim();if(currentSeed===null&&/^\d+$/.test(displayed)){setSeed(Number(displayed));return}let next;do{try{const values=new Uint32Array(1);globalThis.crypto.getRandomValues(values);next=values[0]}catch{next=Math.floor(Math.random()*4294967296)}}while(next===currentSeed);setSeed(next)}
function feature(t){return {odd:t.reduce((a,n)=>a+n%2,0),sum:t.reduce((a,n)=>a+n,0),cons:t.slice(1).filter((n,i)=>n===t[i]+1).length,band:[t.filter(n=>n<=12).length,t.filter(n=>n>=13&&n<=25).length,t.filter(n=>n>=26).length]}}
function gauss(x,a){const m=a.reduce((s,x)=>s+x,0)/a.length,sd=Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length)||1;return Math.exp(-.5*((x-m)/sd)**2)}
function model(h){const ns=Array(38).fill(0),gaps=Array(38).fill(h.length);for(const [w,weight] of [[h.length,.25],[100,.30],[30,.30],[10,.15]]){const sub=h.slice(-w),c=Array(38).fill(0);sub.forEach(r=>r.nums.forEach(n=>c[n]++));for(let n=1;n<=37;n++)ns[n]+=weight*c[n]/(sub.length*7)}for(let i=h.length-1;i>=0;i--)for(const n of h[i].nums)if(gaps[n]===h.length)gaps[n]=h.length-1-i;const maxgap=Math.max(...gaps.slice(1))||1;for(let n=1;n<=37;n++)ns[n]+=.1*gaps[n]/maxgap;const lo=Math.min(...ns.slice(1)),hi=Math.max(...ns.slice(1));for(let n=1;n<=37;n++)ns[n]=hi===lo?.5:(ns[n]-lo)/(hi-lo);const ps=new Map;for(const r of h.slice(-200))for(let i=0;i<7;i++)for(let j=i+1;j<7;j++){const key=r.nums[i]*38+r.nums[j];ps.set(key,(ps.get(key)||0)+1)}const mx=Math.max(1,...ps.values());ps.forEach((v,k)=>ps.set(k,v/mx));const sums=[],odds=[],cons=[],bands=new Map;for(const r of h.slice(-300)){const f=feature(r.nums);sums.push(f.sum);odds.push(f.odd);cons.push(f.cons);const k=f.band.join(',');bands.set(k,(bands.get(k)||0)+1)}return {ns,ps,sums,odds,cons,bands,bmax:Math.max(1,...bands.values())}}
function scorer(m){function params(a){const mean=a.reduce((s,x)=>s+x,0)/a.length;return [mean,Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/a.length)||1]}const sp=params(m.sums),op=params(m.odds),cp=params(m.cons),g=(x,p)=>Math.exp(-.5*((x-p[0])/p[1])**2);return t=>{const f=feature(t);let p=0;for(let i=0;i<7;i++)for(let j=i+1;j<7;j++)p+=m.ps.get(t[i]*38+t[j])||0;return .5*t.reduce((s,n)=>s+m.ns[n],0)/7+.15*p/21+.12*g(f.sum,sp)+.08*g(f.odd,op)+.07*g(f.cons,cp)+.08*(m.bands.get(f.band.join(','))||0)/m.bmax}}
function rng(seed){let s=seed>>>0;return ()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296}}
function sample(random){const p=Array.from({length:37},(_,i)=>i+1);for(let i=0;i<7;i++){const j=i+Math.floor(random()*(37-i));[p[i],p[j]]=[p[j],p[i]]}return p.slice(0,7).sort((a,b)=>a-b)}
function rank(h,c,seed){const score=scorer(model(h)),random=rng(seed),seen=new Set,ranked=[];for(let i=0;i<c;i++){const nums=sample(random),key=nums.join(',');if(!seen.has(key)){seen.add(key);ranked.push({nums,score:score(nums)})}}return ranked.sort((a,b)=>b.score-a.score)}
function select(ranked,n){const out=[];for(const r of ranked){if(out.every(t=>r.nums.filter(x=>t.nums.includes(x)).length<=4))out.push(r);if(out.length===n)break}return out}
function integer(v,min,max,label){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw Error(`${label}は${min}〜${max}の整数にしてください。`);return n}
function locks(v){busy=v;for(const id of ['generate','runTest','upload','tickets','candidates','start','limit','testCandidates']){const el=$(id);if(el)el.disabled=v}}
function renderPrediction(){const box=$('results');box.replaceChildren();predictions.forEach((t,i)=>{const row=document.createElement('div');row.className='ticket';const ix=document.createElement('span');ix.className='index';ix.textContent=fmt(i+1);row.append(ix);const body=document.createElement('div'),balls=document.createElement('div');balls.className='balls';for(const n of t.nums){const ball=document.createElement('span');ball.className='ball';ball.textContent=fmt(n);balls.append(ball)}const f=feature(t.nums),detail=document.createElement('div');detail.className='detail';detail.textContent=`参考スコア ${t.score.toFixed(4)}　合計 ${f.sum}　奇偶 ${f.odd}:${7-f.odd}　連番 ${f.cons}`;body.append(balls,detail);row.append(body);box.append(row)});$('count').textContent=predictions.length+'口';$('cost').textContent=(predictions.length*300).toLocaleString()+'円';$('training').textContent=history.length+'回';$('predictionTitle').textContent=`第${history.at(-1).round+1}回の参考候補`;$('exportPrediction').disabled=!predictions.length}
async function generate(){if(busy)throw Error('処理中です。');const n=integer($('tickets').value,1,10,'口数'),c=integer($('candidates').value,100,50000,'候補数'),seed=integer(currentSeed,0,4294967295,'シード');locks(true);status('候補を採点しています…');try{await pause();const exact=original&&seed===seedDefault&&c===50000&&n<=10;predictions=exact?baseline.slice(0,n):select(rank(history,c,seed),n);$('method').textContent=exact?'元のPython実行結果を使用（候補50,000組・シード20260928）。':'元の採点式を使用。ブラウザ版の乱数生成器はPythonと異なるため、同じシードでも候補は異なります。';renderPrediction();status(predictions.length<n?`${predictions.length}口を生成。重複条件により指定口数に達しませんでした。`:`${predictions.length}口の候補を生成しました。`);return {tickets:predictions}}finally{locks(false)}}
function renderFrequencyChart(counts){
 const chart=$('frequencyChart');if(!chart)return;chart.replaceChildren();const NS='http://www.w3.org/2000/svg',left=52,top=30,bottom=252,step=28,width=19,max=Math.max(1,...counts.slice(1)),tick=Math.max(1,Math.ceil(max/5/10)*10),ceiling=Math.ceil(max/tick)*tick;
 function draw(tag,attrs,text){const el=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,String(v)));if(text!==undefined)el.textContent=text;chart.append(el);return el}
 draw('title',{},'本数字1〜37の出現回数');draw('desc',{},counts.slice(1).map((c,i)=>`${i+1}: ${c}回`).join('、'));
 for(let value=0;value<=ceiling;value+=tick){const y=bottom-(bottom-top)*value/ceiling;draw('line',{x1:left,y1:y,x2:1090,y2:y,stroke:'#d9e3dc','stroke-width':1});draw('text',{x:left-9,y:y+4,'text-anchor':'end',fill:'#64766f','font-size':12},value)}
 draw('text',{x:8,y:15,fill:'#64766f','font-size':12},'回数');
 for(let n=1;n<=37;n++){const x=left+(n-1)*step+5,h=(bottom-top)*counts[n]/ceiling;const bar=draw('rect',{x,y:bottom-h,width,height:h,rx:3,fill:'#1a6558'});const tooltip=document.createElementNS(NS,'title');tooltip.textContent=`数字${fmt(n)}：${counts[n]}回`;bar.append(tooltip);draw('text',{x:x+width/2,y:bottom-h-7,'text-anchor':'middle',fill:'#183d36','font-size':10},counts[n]);draw('text',{x:x+width/2,y:bottom+22,'text-anchor':'middle',fill:'#64766f','font-size':11},fmt(n))}
}
function renderHistory(){const last=history.at(-1);$('period').textContent=`第${history[0].round}〜${last.round}回 / ${last.date||'日付なし'}`;const counts=Array(38).fill(0);history.forEach(r=>r.nums.forEach(n=>counts[n]++));renderFrequencyChart(counts);$('freq').replaceChildren();for(let n=1;n<=37;n++){const d=document.createElement('div'),s=document.createElement('strong'),t=document.createElement('span');s.textContent=fmt(n);t.textContent=counts[n]+'回';d.append(s,t);$('freq').append(d)}$('historyRows').replaceChildren();history.slice(-50).reverse().forEach(r=>tableRow('historyRows',[r.round,r.date,r.nums.map(fmt).join(' · ')]))}
function tableRow(id,values){const tr=document.createElement('tr');values.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});$(id).append(tr)}
function renderTest(){const rows=testResults,N=rows.length;$('testSummary').replaceChildren();if(!N){$('testSummary').textContent='検証結果がありません。';$('testRows').replaceChildren();$('exportTest').disabled=true;return}const p=document.createElement('p');p.className='hint muted';p.textContent=`${N}回を検証 · 各方式10口／回 · 各方式の購入総額目安 ${(N*3000).toLocaleString()}円`;const table=document.createElement('table');table.innerHTML='<thead><tr><th>比較項目</th><th>本方式</th><th>完全ランダム</th></tr></thead>';const body=document.createElement('tbody');for(const [label,key] of [['3個以上一致した回','3plus'],['4個以上一致した回','4plus'],['5個以上一致した回','5plus'],['6個以上一致した回','6plus'],['7個一致した回','7'],['最大一致数の平均','max_hit']]){const tr=document.createElement('tr');const vals=[label,...['model','random'].map(prefix=>key==='max_hit'?(rows.reduce((s,r)=>s+Number(r[prefix+'_'+key]),0)/N).toFixed(3):(()=>{const c=rows.filter(r=>Number(r[prefix+'_'+key])>0).length;return `${c}回 (${(100*c/N).toFixed(1)}%)`})())];vals.forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});body.append(tr)}table.append(body);$('testSummary').append(p,table);$('testRows').replaceChildren();rows.slice(-50).reverse().forEach(r=>tableRow('testRows',[r.round,r.actual,r.model_max_hit,r.random_max_hit]));$('exportTest').disabled=false}
async function runTest(){if(busy)return;const start=integer($('start').value,10,history.length-1,'初期学習回数'),limit=integer($('limit').value,0,history.length,'検証対象'),c=integer($('testCandidates').value,100,50000,'候補数'),first=limit?Math.max(start,history.length-limit):start;locks(true);cancelled=false;$('cancelTest').hidden=false;$('progress').hidden=false;const rows=[];try{for(let i=first;i<history.length;i++){if(cancelled)break;status(`過去検証中 ${rows.length+1} / ${history.length-first}回`);await pause();const chosen=select(rank(history.slice(0,i),c,seedDefault+i),10);if(chosen.length<10)throw Error('10口を選べませんでした。候補数を増やしてください。');const random=rng(seedDefault*10+i),randoms=Array.from({length:10},()=>sample(random)),actual=history[i].nums;const r={round:history[i].round,date:history[i].date,actual:actual.map(fmt).join(' '),cost_10tickets:3000};for(const [prefix,ts] of [['model',chosen.map(t=>t.nums)],['random',randoms]]){const hits=ts.map(t=>t.filter(n=>actual.includes(n)).length);r[prefix+'_max_hit']=Math.max(...hits);r[prefix+'_total_hits']=hits.reduce((s,x)=>s+x,0);for(let k=3;k<=7;k++)r[prefix+'_'+k+(k===7?'':'plus')]=hits.filter(x=>x>=k).length}rows.push(r);$('progress').value=100*rows.length/(history.length-first)}testResults=rows;$('testOrigin').textContent=`Web版で再計算 · 初期学習${start}回 · 候補${c.toLocaleString()}組 · ブラウザ版乱数（添付のPython結果とは異なります）${cancelled?' · 中止時点までの結果':''}`;renderTest();status(cancelled?`${rows.length}回までで中止しました。`:`${rows.length}回の検証が完了しました。`)}finally{locks(false);$('cancelTest').hidden=true;$('progress').hidden=true}}
function csvParse(s){const rows=[];let row=[],v='',quote=false;s=s.replace(/^\uFEFF/,'');for(let i=0;i<s.length;i++){const ch=s[i];if(ch==='"'){if(quote&&s[i+1]==='"'){v+='"';i++}else quote=!quote}else if(ch===','&&!quote){row.push(v);v=''}else if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&s[i+1]==='\n')i++;row.push(v);if(row.some(x=>x.trim()))rows.push(row);row=[];v=''}else v+=ch}if(quote)throw Error('CSVの引用符が閉じていません。');if(v||row.length){row.push(v);rows.push(row)}return rows}
function parseHistory(s){const rows=csvParse(s);if(rows.length<2)throw Error('CSVに抽選データがありません。');const head=rows.shift().map(x=>x.trim().normalize('NFKC')),ri=head.findIndex(x=>/^(round|No|回号|回数)$/i.test(x)),di=head.findIndex(x=>/^(date|日付|抽選日|抽せん日)$/i.test(x)),cols=Array.from({length:7},(_,i)=>head.findIndex(x=>[new RegExp(`^(n|num|number)${i+1}$`,'i'),new RegExp(`^(第)?(数字|本数字)?${i+1}(数字)?$`)].some(p=>p.test(x))));if(ri<0||cols.some(x=>x<0)||new Set(cols).size!==7)throw Error('列名を確認してください。No,抽選日,数字１…数字７ または round,date,n1…n7 に対応しています。');const seen=new Set;const out=rows.map((r,i)=>{const round=integer(r[ri],1,999999,`${i+2}行の回号`);if(seen.has(round))throw Error(`${i+2}行：回号が重複しています。`);seen.add(round);const nums=cols.map(c=>{if(r[c]===undefined||!r[c].trim())throw Error(`${i+2}行：数字が空欄です。`);return integer(r[c],1,37,`${i+2}行の数字`)}).sort((a,b)=>a-b);if(new Set(nums).size!==7)throw Error(`${i+2}行：本数字が重複しています。`);return {round,date:di<0?'':r[di]||'',nums}}).sort((a,b)=>a.round-b.round);if(out.length<10)throw Error('最低10回の履歴が必要です。');return out}
function download(name,rows){if(!rows.length)return;const cols=Object.keys(rows[0]),escape=v=>'"'+String(v??'').replace(/"/g,'""')+'"',text='\uFEFF'+[cols,...rows.map(r=>cols.map(k=>r[k]))].map(row=>row.map(escape).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function safe(fn){try{await fn()}catch(e){status(e.message||'処理に失敗しました。')}}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>{t.classList.toggle('active',t===b);t.setAttribute('aria-current',t===b?'page':'false')});for(const id of ['predict','test','history'])$(id).hidden=id!==b.dataset.page});$('generate').onclick=()=>safe(generate);$('runTest').onclick=()=>safe(runTest);$('cancelTest').onclick=()=>{cancelled=true};$('upload').onchange=()=>safe(async()=>{const file=$('upload').files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('CSVは10MB以下にしてください。');const bytes=await file.arrayBuffer();let text;try{text=new TextDecoder('utf-8',{fatal:true}).decode(bytes)}catch{text=new TextDecoder('shift_jis').decode(bytes)}const next=parseHistory(text);history=next;original=false;testResults=[];renderHistory();renderTest();$('testOrigin').textContent='CSVを入れ替えたため、過去検証を実行してください。';await generate()});$('exportPrediction').onclick=()=>download('loto7_prediction.csv',predictions.map((t,i)=>({ticket:i+1,training_through_round:history.at(-1).round,training_through_date:history.at(-1).date,...Object.fromEntries(t.nums.map((n,j)=>['n'+(j+1),n])),score:t.score,...feature(t.nums),band:feature(t.nums).band.join(':')})));$('exportTest').onclick=()=>download('loto7_backtest_web.csv',testResults);$('exportHistory').onclick=()=>download('loto7_history.csv',history.map(r=>({round:r.round,date:r.date,...Object.fromEntries(r.nums.map((n,i)=>['n'+(i+1),n]))})));
safe(async()=>{initializeSeed();const response=await fetch('data.json');if(!response.ok)throw Error('抽選データを読み込めませんでした。ページを再読み込みしてください。');const data=await response.json();history=data.history;baseline=data.baseline;testResults=data.backtest;renderHistory();renderTest();$('testOrigin').textContent='添付のPython検証結果 · 第201〜695回 · 495回 · 10口／回（再計算前の結果）';locks(false);await generate();if(document.modelContext?.registerTool){try{await document.modelContext.registerTool({name:'generate_loto7_candidates',description:'設定した口数とシードで参考候補を生成し画面に表示する。スコアは当せん確率ではない。',inputSchema:{type:'object',properties:{tickets:{type:'integer',minimum:1,maximum:10},seed:{type:'integer',minimum:0,maximum:4294967295}},required:['tickets','seed'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{if(busy)throw Error('処理中です。');integer(input.tickets,1,10,'口数');integer(input.seed,0,4294967295,'シード');$('tickets').value=String(input.tickets);setSeed(input.seed);return generate()}})}catch{}}});
